# -*- coding: utf-8 -*-
"""week3 A108260064 陳俊豪.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQ6XQ7IN6nIornLlYWusX8Wrwx8jvyj0
"""

print("Hello World")

print("我是陳俊豪")